In [97]:
import pandas as pd

st = pd.read_csv("La_Liga/2021-2022/ESP_La_Liga_2122_standard.csv",header=[0,1])
st.head(5)
#verificando a estrutura do dataframe

              league             season               team             player  \
  Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1 Unnamed: 3_level_1
0        ESP-La Liga               2122             Alavés     Antonio Sivera
1        ESP-La Liga               2122             Alavés  Facundo Pellistri
2        ESP-La Liga               2122             Alavés   Fernando Pacheco
3        ESP-La Liga               2122             Alavés    Florian Lejeune
4        ESP-La Liga               2122             Alavés  Gonzalo Escalante

              nation                pos                age               born  \
  Unnamed: 4_level_1 Unnamed: 5_level_1 Unnamed: 6_level_1 Unnamed: 7_level_1
0                ESP                 GK                 24               1996
1                URU              MF,FW                 19               2001
2                ESP                 GK                 29               1992
3                FRA                 DF                 30               1991
4                ARG                 MF                 28               1993

  Playing Time         ... Performance                    Per 90 Minutes       \
            MP Starts  ...        G-PK PK PKatt CrdY CrdR            Gls  Ast
0            4      3  ...           0  0     0    1    0           0.00  0.0
1           21      6  ...           0  0     0    0    0           0.00  0.0
2           34     34  ...           0  0     0    1    0           0.00  0.0
3           30     30  ...           0  0     0    9    1           0.00  0.0
4           17     15  ...           5  0     0    8    1           0.35  0.0


    G+A  G-PK G+A-PK
0  0.00  0.00   0.00
1  0.00  0.00   0.00
2  0.00  0.00   0.00
3  0.00  0.00   0.00
4  0.35  0.35   0.35

[5 rows x 25 columns]

In [98]:
from pathlib import Path

pasta = Path("C:/Users/Gustavo/Documents/DadosFut")

arquivos = list(pasta.rglob("*.csv"))

print(f"Arquivos encontrados: {len(arquivos)}")

dfs = []

for arquivo in arquivos:
    df = pd.read_csv(arquivo, header=[0, 1])
    dfs.append(df)

df_bruto = pd.concat(dfs, ignore_index=True)

df_bruto.to_csv(
    "C:/Users/Gustavo/Documents/DadosFut/DadosFUTBrutos.csv",
    index=False
)

Arquivos encontrados: 25

In [99]:
df_bruto = pd.read_csv("C:/Users/Gustavo/Documents/DadosFut/DadosFUTBrutos.csv", header=[0, 1]) # leio o arquivo bruto que foi gerado, utilizando header=[0,1] para manter a estrutura de multi-index do cabeçalho
df_bruto.head(5)

              league             season               team             player  \
  Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1 Unnamed: 3_level_1
0        ITA-Serie A               2122           Atalanta    Alassane Sidibe
1        ITA-Serie A               2122           Atalanta  Aleksei Miranchuk
2        ITA-Serie A               2122           Atalanta     Berat Djimsiti
3        ITA-Serie A               2122           Atalanta  Davide Zappacosta
4        ITA-Serie A               2122           Atalanta       Duván Zapata

              nation                pos                age               born  \
  Unnamed: 4_level_1 Unnamed: 5_level_1 Unnamed: 6_level_1 Unnamed: 7_level_1
0                CIV                 MF               19.0             2002.0
1                RUS              MF,FW               25.0             1995.0
2                ALB                 DF               28.0             1993.0
3                ITA              MF,DF               29.0             1992.0
4                COL                 FW               30.0             1991.0

  Playing Time         ... Performance                    Per 90 Minutes  \
            MP Starts  ...        G-PK PK PKatt CrdY CrdR            Gls
0            1      0  ...           0  0     0    0    0           0.00
1           19      7  ...           2  0     0    0    0           0.23
2           31     25  ...           1  0     0    6    0           0.04
3           34     29  ...           1  0     0    6    0           0.04
4           24     20  ...           7  3     3    3    0           0.52


    Ast   G+A  G-PK G+A-PK
0  0.00  0.00  0.00   0.00
1  0.58  0.82  0.23   0.82
2  0.04  0.08  0.04   0.08
3  0.19  0.23  0.04   0.23
4  0.21  0.73  0.37   0.57

[5 rows x 25 columns]

In [100]:
df_bruto.columns

#Verifiquei que Temos um MultiIndex no cabeçalho, então vamos renomear as colunas para facilitar a manipulação dos dados.

MultiIndex([(        'league', 'Unnamed: 0_level_1'),
            (        'season', 'Unnamed: 1_level_1'),
            (          'team', 'Unnamed: 2_level_1'),
            (        'player', 'Unnamed: 3_level_1'),
            (        'nation', 'Unnamed: 4_level_1'),
            (           'pos', 'Unnamed: 5_level_1'),
            (           'age', 'Unnamed: 6_level_1'),
            (          'born', 'Unnamed: 7_level_1'),
            (  'Playing Time',                 'MP'),
            (  'Playing Time',             'Starts'),
            (  'Playing Time',                'Min'),
            (  'Playing Time',                '90s'),
            (   'Performance',                'Gls'),
            (   'Performance',                'Ast'),
            (   'Performance',                'G+A'),
            (   'Performance',               'G-PK'),
            (   'Performance',                 'PK'),
            (   'Performance',              'PKatt'),
            (   'Performance',               'CrdY'),
            (   'Performance',               'CrdR'),
            ('Per 90 Minutes',                'Gls'),
            ('Per 90 Minutes',                'Ast'),
            ('Per 90 Minutes',                'G+A'),
            ('Per 90 Minutes',               'G-PK'),
            ('Per 90 Minutes',             'G+A-PK')],
           )

In [101]:
df_bruto.columns = df_bruto.columns.map('_'.join) #vou juntar o nivel 1 e 0 e transformar em uma unica coluna, separando por _

In [102]:
df_bruto.columns 
#colunas juntas, agora vamos renomear

Index(['league_Unnamed: 0_level_1', 'season_Unnamed: 1_level_1',
       'team_Unnamed: 2_level_1', 'player_Unnamed: 3_level_1',
       'nation_Unnamed: 4_level_1', 'pos_Unnamed: 5_level_1',
       'age_Unnamed: 6_level_1', 'born_Unnamed: 7_level_1', 'Playing Time_MP',
       'Playing Time_Starts', 'Playing Time_Min', 'Playing Time_90s',
       'Performance_Gls', 'Performance_Ast', 'Performance_G+A',
       'Performance_G-PK', 'Performance_PK', 'Performance_PKatt',
       'Performance_CrdY', 'Performance_CrdR', 'Per 90 Minutes_Gls',
       'Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G-PK',
       'Per 90 Minutes_G+A-PK'],
      dtype='str')

In [103]:
df_bruto = df_bruto.rename(columns={
    'league_Unnamed: 0_level_1': 'league',
    'season_Unnamed: 1_level_1': 'season',
    'team_Unnamed: 2_level_1': 'team',
    'player_Unnamed: 3_level_1': 'player',
    'nation_Unnamed: 4_level_1': 'nation',
    'pos_Unnamed: 5_level_1': 'pos',
    'age_Unnamed: 6_level_1': 'age',
    'born_Unnamed: 7_level_1': 'born',

    'Playing Time_MP': 'MP',
    'Playing Time_Starts': 'Starts',
    'Playing Time_Min': 'Min',
    'Playing Time_90s': '90s',

    'Performance_Gls': 'Gls',
    'Performance_Ast': 'Ast',
    'Performance_G+A': 'G+A',
    'Performance_G-PK': 'G-PK',

    'Per 90 Minutes_Gls': 'Gls_90',
    'Per 90 Minutes_Ast': 'Ast_90',
    'Per 90 Minutes_G+A': 'G+A_90',
    'Per 90 Minutes_G-PK': 'G-PK_90',
    'Per 90 Minutes_G+A-PK': 'G+A-PK_90'
})

#colunas renomeadas, agora vamos selecionar apenas as colunas que queremos manter

In [104]:
df_bruto = df_bruto[
    [
        'league',
        'season',
        'team',
        'player',
        'nation',
        'pos',
        'age',
        'MP',
        'Starts',
        'Min',
        'Gls',
        'Ast',
        'G+A',
        'G-PK',
        'Gls_90',
        'Ast_90',
        'G+A_90'
    ]
]

#selecionada colunas que vamos utilizar no projeto.

In [105]:

df_bruto['pos'].value_counts() #verifiquei a quantidade de jogadores por posição, e percebi que temos jogadores de todas as posições, então vamos selecionar apenas os jogadores que são meio-campistas ou atacantes, pois são os que mais contribuem para o ataque do time.

pos
MF       4458
DF       3603
FW       1929
MF,FW    1086
GK       1034
FW,MF     863
DF,MF     789
MF,DF     575
DF,FW      17
FW,DF       2
Name: count, dtype: int64

In [106]:
df_bruto = df_bruto[df_bruto['pos'].str.contains('MF|FW')] #Seleciono apenas os jogadores que são meio-campistas ou atacantes, pois são os que mais contribuem para o ataque do time.

In [ ]:
df_bruto.duplicated().sum() #verifico se tem valores duplicados, caso tenha, vou remover, pois não faz sentido ter jogadores duplicados no mesmo time.

np.int64(0)

In [108]:
df_bruto = df_bruto[df_bruto['Min'] > 900] #seleciono apenas os jogadores que jogaram mais de 900 minutos, pois são os que mais contribuíram para o time, e são os que mais tem chances de serem titulares.

In [109]:
df_bruto.shape #verifico a quantidade de jogadores que sobraram.

(5172, 17)

In [110]:
df_bruto['pos'].value_counts()

pos
MF       2329
FW        769
MF,FW     729
DF,MF     499
FW,MF     440
MF,DF     403
DF,FW       3
Name: count, dtype: int64

In [111]:
#Traduzindo colunas para português
df_bruto = df_bruto.rename(columns={
    'league': 'liga',
    'season': 'temporada',
    'team': 'time',
    'player': 'jogador',
    'nation': 'nacionalidade',
    'pos': 'posicao',
    'age': 'idade',
    'MP': 'partidas',
    'Starts': 'titularidades',
    'Min': 'minutos',
    'Gls': 'gols',
    'Ast': 'assistencias',
    'G+A': 'gols_assistencias',
    'G-PK': 'gols_sem_penaltis',
    'Gls_90': 'gols_90',
    'Ast_90': 'assistencias_90',
    'G+A_90': 'gols_assistencias_90'
})

In [112]:
df_bruto.isna().sum() #verifiquei que nao existem valores nulos, então podemos prosseguir com a exportaçao do csv para DadosFUTLimpos.csv, que será o arquivo que vamos utilizar para a analise dos dados.

liga                    0
temporada               0
time                    0
jogador                 0
nacionalidade           0
posicao                 0
idade                   0
partidas                0
titularidades           0
minutos                 0
gols                    0
assistencias            0
gols_assistencias       0
gols_sem_penaltis       0
gols_90                 0
assistencias_90         0
gols_assistencias_90    0
dtype: int64

In [ ]:
df_bruto.to_csv("C:/Users/Gustavo/Documents/DadosFut/DadosFUTLimpos.csv", index=False) #importo para o arquivo DadosFUTLimpos.csv, que será o arquivo que vamos utilizar para a analise dos dados.